# a fenykepek lehetseges kategoriai, thx to fotozz.hu
CATEGORIES = ['absztrakt',
              'abszurd',
              'akt',
              'autók',
              'állatfotók',
              'barlangfotók',
              'családi/emlékkép',
              'csendélet',
              'csillagászat/égbolt',
              'digit. illusztráció',
              'divat',
              'dokumentumfotók',
              'életképek',
              'elkapott pillanatok',
              'glamour',
              'hangulatképek',
              'humor',
              'infravörös fotók',
              'koncert - színpad',
              'légifotók',
              'makró',
              'panoráma',
              'portré',
              'riport',
              'sport',
              'szociofotók',
              'tájkép',
              'tárgyfotók',
              'természet',
              'utcaifotók',
              'város, építészet',
              'vízalatti fotók',
              'egyéb']
