INSERT INTO Countries VALUES (0, 'Algéria', 'Afrika', 'algeria');
INSERT INTO Countries VALUES (1, 'Angola', 'Afrika', 'angola');
INSERT INTO Countries VALUES (2, 'Benin', 'Afrika', 'benin');
INSERT INTO Countries VALUES (3, 'Botswana', 'Afrika', 'botswana');
INSERT INTO Countries VALUES (4, 'Burkina Faso', 'Afrika', 'burkinafas');
INSERT INTO Countries VALUES (5, 'Burundi', 'Afrika', 'burundi');
INSERT INTO Countries VALUES (6, 'Comore-szigetek', 'Afrika', 'comoreszig');
INSERT INTO Countries VALUES (7, 'Csád', 'Afrika', 'csad');
INSERT INTO Countries VALUES (8, 'Dzsibuti', 'Afrika', 'dzsibuti');
INSERT INTO Countries VALUES (9, 'Dél-Afrika', 'Afrika', 'delafrika');
INSERT INTO Countries VALUES (10, 'Egyenlítői-Guinea', 'Afrika', 'egyenlitoi');
INSERT INTO Countries VALUES (11, 'Egyiptom', 'Afrika', 'egyiptom');
INSERT INTO Countries VALUES (12, 'Elefántcsontpart', 'Afrika', 'elefantcso');
INSERT INTO Countries VALUES (13, 'Eritrea', 'Afrika', 'eritrea');
INSERT INTO Countries VALUES (14, 'Etiópia', 'Afrika', 'etiopia');
INSERT INTO Countries VALUES (15, 'Gabon', 'Afrika', 'gabon');
INSERT INTO Countries VALUES (16, 'Gambia', 'Afrika', 'gambia');
INSERT INTO Countries VALUES (17, 'Ghána', 'Afrika', 'ghana');
INSERT INTO Countries VALUES (18, 'Guinea', 'Afrika', 'guinea');
INSERT INTO Countries VALUES (19, 'Guinea-Bissau', 'Afrika', 'guineabiss');
INSERT INTO Countries VALUES (20, 'Kamerun', 'Afrika', 'kamerun');
INSERT INTO Countries VALUES (21, 'Kenya', 'Afrika', 'kenya');
INSERT INTO Countries VALUES (22, 'Kongó', 'Afrika', 'kongo');
INSERT INTO Countries VALUES (23, 'Kongó - Kinshasa', 'Afrika', 'kongokinsh');
INSERT INTO Countries VALUES (24, 'Közép-afrikai Köztársaság', 'Afrika', 'kozepafrik');
INSERT INTO Countries VALUES (25, 'Lesotho', 'Afrika', 'lesotho');
INSERT INTO Countries VALUES (26, 'Libéria', 'Afrika', 'liberia');
INSERT INTO Countries VALUES (27, 'Líbia', 'Afrika', 'libia');
INSERT INTO Countries VALUES (28, 'Madagaszkár', 'Afrika', 'madagaszka');
INSERT INTO Countries VALUES (29, 'Malawi', 'Afrika', 'malawi');
INSERT INTO Countries VALUES (30, 'Mali', 'Afrika', 'mali');
INSERT INTO Countries VALUES (31, 'Marokkó', 'Afrika', 'marokko');
INSERT INTO Countries VALUES (32, 'Mauritius', 'Afrika', 'mauritius');
INSERT INTO Countries VALUES (33, 'Mauritánia', 'Afrika', 'mauritania');
INSERT INTO Countries VALUES (34, 'Mayotte', 'Afrika', 'mayotte');
INSERT INTO Countries VALUES (35, 'Mozambik', 'Afrika', 'mozambik');
INSERT INTO Countries VALUES (36, 'Namíbia', 'Afrika', 'namibia');
INSERT INTO Countries VALUES (37, 'Niger', 'Afrika', 'niger');
INSERT INTO Countries VALUES (38, 'Nigéria', 'Afrika', 'nigeria');
INSERT INTO Countries VALUES (39, 'Nyugat-Szahara', 'Afrika', 'nyugatszah');
INSERT INTO Countries VALUES (40, 'Reunion', 'Afrika', 'reunion');
INSERT INTO Countries VALUES (41, 'Ruanda', 'Afrika', 'ruanda');
INSERT INTO Countries VALUES (42, 'Sao Tomé és Príncipe', 'Afrika', 'saotomeesp');
INSERT INTO Countries VALUES (43, 'Seychelle-szigetek', 'Afrika', 'seychelles');
INSERT INTO Countries VALUES (44, 'Sierra Leone', 'Afrika', 'sierraleon');
INSERT INTO Countries VALUES (45, 'Szenegál', 'Afrika', 'szenegal');
INSERT INTO Countries VALUES (46, 'Szent Helena', 'Afrika', 'szenthelen');
INSERT INTO Countries VALUES (47, 'Szomália', 'Afrika', 'szomalia');
INSERT INTO Countries VALUES (48, 'Szudán', 'Afrika', 'szudan');
INSERT INTO Countries VALUES (49, 'Szváziföld', 'Afrika', 'szvazifold');
INSERT INTO Countries VALUES (50, 'Tanzánia', 'Afrika', 'tanzania');
INSERT INTO Countries VALUES (51, 'Togo', 'Afrika', 'togo');
INSERT INTO Countries VALUES (52, 'Tunézia', 'Afrika', 'tunezia');
INSERT INTO Countries VALUES (53, 'Uganda', 'Afrika', 'uganda');
INSERT INTO Countries VALUES (54, 'Zambia', 'Afrika', 'zambia');
INSERT INTO Countries VALUES (55, 'Zimbabwe', 'Afrika', 'zimbabwe');
INSERT INTO Countries VALUES (56, 'Zöld-foki Köztársaság', 'Afrika', 'zoldfokiko');
INSERT INTO Countries VALUES (57, 'Amerikai Virgin-szigetek', 'Amerika', 'amerikaivi');
INSERT INTO Countries VALUES (58, 'Anguilla', 'Amerika', 'anguilla');
INSERT INTO Countries VALUES (59, 'Antigua és Barbuda', 'Amerika', 'antiguaesb');
INSERT INTO Countries VALUES (60, 'Argentína', 'Amerika', 'argentina');
INSERT INTO Countries VALUES (61, 'Aruba', 'Amerika', 'aruba');
INSERT INTO Countries VALUES (62, 'Bahamák', 'Amerika', 'bahamak');
INSERT INTO Countries VALUES (63, 'Barbados', 'Amerika', 'barbados');
INSERT INTO Countries VALUES (64, 'Belize', 'Amerika', 'belize');
INSERT INTO Countries VALUES (65, 'Bermuda', 'Amerika', 'bermuda');
INSERT INTO Countries VALUES (66, 'Bolívia', 'Amerika', 'bolivia');
INSERT INTO Countries VALUES (67, 'Brazília', 'Amerika', 'brazilia');
INSERT INTO Countries VALUES (68, 'Brit Virgin-szigetek', 'Amerika', 'britvirgin');
INSERT INTO Countries VALUES (69, 'Chile', 'Amerika', 'chile');
INSERT INTO Countries VALUES (70, 'Costa Rica', 'Amerika', 'costarica');
INSERT INTO Countries VALUES (71, 'Dominika', 'Amerika', 'dominika');
INSERT INTO Countries VALUES (72, 'Dominikai Köztársaság', 'Amerika', 'dominikaik');
INSERT INTO Countries VALUES (73, 'Ecuador', 'Amerika', 'ecuador');
INSERT INTO Countries VALUES (74, 'Egyesült Államok', 'Amerika', 'egyesultal');
INSERT INTO Countries VALUES (75, 'Falkland-szigetek', 'Amerika', 'falklandsz');
INSERT INTO Countries VALUES (76, 'Francia Guyana', 'Amerika', 'franciaguy');
INSERT INTO Countries VALUES (77, 'Grenada', 'Amerika', 'grenada');
INSERT INTO Countries VALUES (78, 'Grönland', 'Amerika', 'gronland');
INSERT INTO Countries VALUES (79, 'Guadeloupe', 'Amerika', 'guadeloupe');
INSERT INTO Countries VALUES (80, 'Guatemala', 'Amerika', 'guatemala');
INSERT INTO Countries VALUES (81, 'Guyana', 'Amerika', 'guyana');
INSERT INTO Countries VALUES (82, 'Haiti', 'Amerika', 'haiti');
INSERT INTO Countries VALUES (83, 'Holland Antillák', 'Amerika', 'hollandant');
INSERT INTO Countries VALUES (84, 'Honduras', 'Amerika', 'honduras');
INSERT INTO Countries VALUES (85, 'Jamaica', 'Amerika', 'jamaica');
INSERT INTO Countries VALUES (86, 'Kajmán-szigetek', 'Amerika', 'kajmanszig');
INSERT INTO Countries VALUES (87, 'Kanada', 'Amerika', 'kanada');
INSERT INTO Countries VALUES (88, 'Kolumbia', 'Amerika', 'kolumbia');
INSERT INTO Countries VALUES (89, 'Kuba', 'Amerika', 'kuba');
INSERT INTO Countries VALUES (90, 'Martinique', 'Amerika', 'martinique');
INSERT INTO Countries VALUES (91, 'Mexikó', 'Amerika', 'mexiko');
INSERT INTO Countries VALUES (92, 'Montserrat', 'Amerika', 'montserrat');
INSERT INTO Countries VALUES (93, 'Nicaragua', 'Amerika', 'nicaragua');
INSERT INTO Countries VALUES (94, 'Panama', 'Amerika', 'panama');
INSERT INTO Countries VALUES (95, 'Paraguay', 'Amerika', 'paraguay');
INSERT INTO Countries VALUES (96, 'Peru', 'Amerika', 'peru');
INSERT INTO Countries VALUES (97, 'Puerto Rico', 'Amerika', 'puertorico');
INSERT INTO Countries VALUES (98, 'Saint Barthélemy', 'Amerika', 'saintbarth');
INSERT INTO Countries VALUES (99, 'Saint Kitts és Nevis', 'Amerika', 'saintkitts');
INSERT INTO Countries VALUES (100, 'Saint Martin', 'Amerika', 'saintmarti');
INSERT INTO Countries VALUES (101, 'Saint Pierre és Miquelon', 'Amerika', 'saintpierr');
INSERT INTO Countries VALUES (102, 'Saint Vincent és Grenadines', 'Amerika', 'saintvince');
INSERT INTO Countries VALUES (103, 'Salvador', 'Amerika', 'salvador');
INSERT INTO Countries VALUES (104, 'Santa Lucia', 'Amerika', 'santalucia');
INSERT INTO Countries VALUES (105, 'Suriname', 'Amerika', 'suriname');
INSERT INTO Countries VALUES (106, 'Trinidad és Tobago', 'Amerika', 'trinidades');
INSERT INTO Countries VALUES (107, 'Turks- és Caicos-szigetek', 'Amerika', 'turksescai');
INSERT INTO Countries VALUES (108, 'Uruguay', 'Amerika', 'uruguay');
INSERT INTO Countries VALUES (109, 'Venezuela', 'Amerika', 'venezuela');
INSERT INTO Countries VALUES (110, 'Aland-szigetek', 'Európa', 'alandszige');
INSERT INTO Countries VALUES (111, 'Albánia', 'Európa', 'albania');
INSERT INTO Countries VALUES (112, 'Andorra', 'Európa', 'andorra');
INSERT INTO Countries VALUES (113, 'Ausztria', 'Európa', 'ausztria');
INSERT INTO Countries VALUES (114, 'Belgium', 'Európa', 'belgium');
INSERT INTO Countries VALUES (115, 'Bosznia-Hercegovina', 'Európa', 'boszniaher');
INSERT INTO Countries VALUES (116, 'Bulgária', 'Európa', 'bulgaria');
INSERT INTO Countries VALUES (117, 'Ciprus', 'Európa', 'ciprus');
INSERT INTO Countries VALUES (118, 'Csehország', 'Európa', 'csehorszag');
INSERT INTO Countries VALUES (119, 'Dánia', 'Európa', 'dania');
INSERT INTO Countries VALUES (120, 'Egyesült Királyság', 'Európa', 'egyesultki');
INSERT INTO Countries VALUES (121, 'Fehéroroszország', 'Európa', 'feherorosz');
INSERT INTO Countries VALUES (122, 'Feröer-szigetek', 'Európa', 'feroerszig');
INSERT INTO Countries VALUES (123, 'Finnország', 'Európa', 'finnorszag');
INSERT INTO Countries VALUES (124, 'Franciaország', 'Európa', 'franciaors');
INSERT INTO Countries VALUES (125, 'Gibraltár', 'Európa', 'gibraltar');
INSERT INTO Countries VALUES (126, 'Guernsey', 'Európa', 'guernsey');
INSERT INTO Countries VALUES (127, 'Görögország', 'Európa', 'gorogorsza');
INSERT INTO Countries VALUES (128, 'Hollandia', 'Európa', 'hollandia');
INSERT INTO Countries VALUES (129, 'Horvátország', 'Európa', 'horvatorsz');
INSERT INTO Countries VALUES (130, 'Izland', 'Európa', 'izland');
INSERT INTO Countries VALUES (131, 'Jersey', 'Európa', 'jersey');
INSERT INTO Countries VALUES (132, 'Lengyelország', 'Európa', 'lengyelors');
INSERT INTO Countries VALUES (133, 'Lettország', 'Európa', 'lettorszag');
INSERT INTO Countries VALUES (134, 'Liechtenstein', 'Európa', 'liechtenst');
INSERT INTO Countries VALUES (135, 'Litvánia', 'Európa', 'litvania');
INSERT INTO Countries VALUES (136, 'Luxemburg', 'Európa', 'luxemburg');
INSERT INTO Countries VALUES (137, 'Macedónia', 'Európa', 'macedonia');
INSERT INTO Countries VALUES (138, 'Magyarország', 'Európa', 'magyarorsz');
INSERT INTO Countries VALUES (139, 'Man-sziget', 'Európa', 'mansziget');
INSERT INTO Countries VALUES (140, 'Moldova', 'Európa', 'moldova');
INSERT INTO Countries VALUES (141, 'Monaco', 'Európa', 'monaco');
INSERT INTO Countries VALUES (142, 'Montenegró', 'Európa', 'montenegro');
INSERT INTO Countries VALUES (143, 'Málta', 'Európa', 'malta');
INSERT INTO Countries VALUES (144, 'Norvégia', 'Európa', 'norvegia');
INSERT INTO Countries VALUES (145, 'Németország', 'Európa', 'nemetorsza');
INSERT INTO Countries VALUES (146, 'Olaszország', 'Európa', 'olaszorsza');
INSERT INTO Countries VALUES (147, 'Oroszország', 'Európa', 'oroszorsza');
INSERT INTO Countries VALUES (148, 'Portugália', 'Európa', 'portugalia');
INSERT INTO Countries VALUES (149, 'Románia', 'Európa', 'romania');
INSERT INTO Countries VALUES (150, 'San Marino', 'Európa', 'sanmarino');
INSERT INTO Countries VALUES (151, 'Spanyolország', 'Európa', 'spanyolors');
INSERT INTO Countries VALUES (152, 'Svalbard és Jan Mayen', 'Európa', 'svalbardes');
INSERT INTO Countries VALUES (153, 'Svájc', 'Európa', 'svajc');
INSERT INTO Countries VALUES (154, 'Svédország', 'Európa', 'svedorszag');
INSERT INTO Countries VALUES (155, 'Szerbia', 'Európa', 'szerbia');
INSERT INTO Countries VALUES (156, 'Szerbia és Montenegró', 'Európa', 'szerbiaesm');
INSERT INTO Countries VALUES (157, 'Szlovákia', 'Európa', 'szlovakia');
INSERT INTO Countries VALUES (158, 'Szlovénia', 'Európa', 'szlovenia');
INSERT INTO Countries VALUES (159, 'Ukrajna', 'Európa', 'ukrajna');
INSERT INTO Countries VALUES (160, 'Vatikán', 'Európa', 'vatikan');
INSERT INTO Countries VALUES (161, 'Észtország', 'Európa', 'esztorszag');
INSERT INTO Countries VALUES (162, 'Írország', 'Európa', 'irorszag');
INSERT INTO Countries VALUES (163, 'Afganisztán', 'Ázsia', 'afganiszta');
INSERT INTO Countries VALUES (164, 'Azerbajdzsán', 'Ázsia', 'azerbajdzs');
INSERT INTO Countries VALUES (165, 'Bahrein', 'Ázsia', 'bahrein');
INSERT INTO Countries VALUES (166, 'Banglades', 'Ázsia', 'banglades');
INSERT INTO Countries VALUES (167, 'Bhután', 'Ázsia', 'bhutan');
INSERT INTO Countries VALUES (168, 'Brunei', 'Ázsia', 'brunei');
INSERT INTO Countries VALUES (169, 'Ciprus', 'Ázsia', 'ciprus');
INSERT INTO Countries VALUES (170, 'Dél-Korea', 'Ázsia', 'delkorea');
INSERT INTO Countries VALUES (171, 'Egyesült Arab Emirátus', 'Ázsia', 'egyesultar');
INSERT INTO Countries VALUES (172, 'Fülöp-szigetek', 'Ázsia', 'fulopszige');
INSERT INTO Countries VALUES (173, 'Grúzia', 'Ázsia', 'gruzia');
INSERT INTO Countries VALUES (174, 'Hongkong S.A.R, Kína', 'Ázsia', 'hongkongs.');
INSERT INTO Countries VALUES (175, 'India', 'Ázsia', 'india');
INSERT INTO Countries VALUES (176, 'Indonézia', 'Ázsia', 'indonezia');
INSERT INTO Countries VALUES (177, 'Irak', 'Ázsia', 'irak');
INSERT INTO Countries VALUES (178, 'Irán', 'Ázsia', 'iran');
INSERT INTO Countries VALUES (179, 'Izrael', 'Ázsia', 'izrael');
INSERT INTO Countries VALUES (180, 'Japán', 'Ázsia', 'japan');
INSERT INTO Countries VALUES (181, 'Jemen', 'Ázsia', 'jemen');
INSERT INTO Countries VALUES (182, 'Jordánia', 'Ázsia', 'jordania');
INSERT INTO Countries VALUES (183, 'Kambodzsa', 'Ázsia', 'kambodzsa');
INSERT INTO Countries VALUES (184, 'Katar', 'Ázsia', 'katar');
INSERT INTO Countries VALUES (185, 'Kazahsztán', 'Ázsia', 'kazahsztan');
INSERT INTO Countries VALUES (186, 'Kelet-Timor', 'Ázsia', 'kelettimor');
INSERT INTO Countries VALUES (187, 'Kirgizisztán', 'Ázsia', 'kirgiziszt');
INSERT INTO Countries VALUES (188, 'Kuvait', 'Ázsia', 'kuvait');
INSERT INTO Countries VALUES (189, 'Kína', 'Ázsia', 'kina');
INSERT INTO Countries VALUES (190, 'Laosz', 'Ázsia', 'laosz');
INSERT INTO Countries VALUES (191, 'Libanon', 'Ázsia', 'libanon');
INSERT INTO Countries VALUES (192, 'Makaó SAR Kína', 'Ázsia', 'makaosarki');
INSERT INTO Countries VALUES (193, 'Malajzia', 'Ázsia', 'malajzia');
INSERT INTO Countries VALUES (194, 'Maldív-szigetek', 'Ázsia', 'maldivszig');
INSERT INTO Countries VALUES (195, 'Mianmar', 'Ázsia', 'mianmar');
INSERT INTO Countries VALUES (196, 'Mongólia', 'Ázsia', 'mongolia');
INSERT INTO Countries VALUES (197, 'Nepál', 'Ázsia', 'nepal');
INSERT INTO Countries VALUES (198, 'Omán', 'Ázsia', 'oman');
INSERT INTO Countries VALUES (199, 'Pakisztán', 'Ázsia', 'pakisztan');
INSERT INTO Countries VALUES (200, 'Palesztin Terület', 'Ázsia', 'palesztint');
INSERT INTO Countries VALUES (201, 'Srí Lanka', 'Ázsia', 'srilanka');
INSERT INTO Countries VALUES (202, 'Szaúd-Arábia', 'Ázsia', 'szaudarabi');
INSERT INTO Countries VALUES (203, 'Szingapúr', 'Ázsia', 'szingapur');
INSERT INTO Countries VALUES (204, 'Szíria', 'Ázsia', 'sziria');
INSERT INTO Countries VALUES (205, 'Tadzsikisztán', 'Ázsia', 'tadzsikisz');
INSERT INTO Countries VALUES (206, 'Tajvan', 'Ázsia', 'tajvan');
INSERT INTO Countries VALUES (207, 'Thaiföld', 'Ázsia', 'thaifold');
INSERT INTO Countries VALUES (208, 'Törökország', 'Ázsia', 'torokorsza');
INSERT INTO Countries VALUES (209, 'Türkmenisztán', 'Ázsia', 'turkmenisz');
INSERT INTO Countries VALUES (210, 'Vietnam', 'Ázsia', 'vietnam');
INSERT INTO Countries VALUES (211, 'Észak-Korea', 'Ázsia', 'eszakkorea');
INSERT INTO Countries VALUES (212, 'Örményország', 'Ázsia', 'ormenyorsz');
INSERT INTO Countries VALUES (213, 'Üzbegisztán', 'Ázsia', 'uzbegiszta');
INSERT INTO Countries VALUES (214, 'Amerikai Csendes-óceáni Szigetek', 'Óceánia', 'amerikaics');
INSERT INTO Countries VALUES (215, 'Amerikai Szamoa', 'Óceánia', 'amerikaisz');
INSERT INTO Countries VALUES (216, 'Antarktisz', 'Óceánia', 'antarktisz');
INSERT INTO Countries VALUES (217, 'Ausztrália', 'Óceánia', 'ausztralia');
INSERT INTO Countries VALUES (218, 'Bouvet-sziget', 'Óceánia', 'bouvetszig');
INSERT INTO Countries VALUES (219, 'Brit Indiai Oceán', 'Óceánia', 'britindiai');
INSERT INTO Countries VALUES (220, 'Cook-szigetek', 'Óceánia', 'cooksziget');
INSERT INTO Countries VALUES (221, 'Dél Grúzia és a Déli Szendvics-szigetek', 'Óceánia', 'delgruziae');
INSERT INTO Countries VALUES (222, 'Fidzsi', 'Óceánia', 'fidzsi');
INSERT INTO Countries VALUES (223, 'Francia Déli Területek', 'Óceánia', 'franciadel');
INSERT INTO Countries VALUES (224, 'Francia Polinézia', 'Óceánia', 'franciapol');
INSERT INTO Countries VALUES (225, 'Guam', 'Óceánia', 'guam');
INSERT INTO Countries VALUES (226, 'Heard és McDonald Szigetek', 'Óceánia', 'heardesmcd');
INSERT INTO Countries VALUES (227, 'Karácsony-szigetek', 'Óceánia', 'karacsonys');
INSERT INTO Countries VALUES (228, 'Kiribati', 'Óceánia', 'kiribati');
INSERT INTO Countries VALUES (229, 'Kókusz-szigetek', 'Óceánia', 'kokuszszig');
INSERT INTO Countries VALUES (230, 'Marshall-szigetek', 'Óceánia', 'marshallsz');
INSERT INTO Countries VALUES (231, 'Mikronézia', 'Óceánia', 'mikronezia');
INSERT INTO Countries VALUES (232, 'Nauru', 'Óceánia', 'nauru');
INSERT INTO Countries VALUES (233, 'Niue', 'Óceánia', 'niue');
INSERT INTO Countries VALUES (234, 'Norfolk-sziget', 'Óceánia', 'norfolkszi');
INSERT INTO Countries VALUES (235, 'Palau', 'Óceánia', 'palau');
INSERT INTO Countries VALUES (236, 'Pitcairn-sziget', 'Óceánia', 'pitcairnsz');
INSERT INTO Countries VALUES (237, 'Pápua Új-Guinea', 'Óceánia', 'papuaujgui');
INSERT INTO Countries VALUES (238, 'Salamon-szigetek', 'Óceánia', 'salamonszi');
INSERT INTO Countries VALUES (239, 'Szamoa', 'Óceánia', 'szamoa');
INSERT INTO Countries VALUES (240, 'Tokelau', 'Óceánia', 'tokelau');
INSERT INTO Countries VALUES (241, 'Tonga', 'Óceánia', 'tonga');
INSERT INTO Countries VALUES (242, 'Tuvalu', 'Óceánia', 'tuvalu');
INSERT INTO Countries VALUES (243, 'Vanuatu', 'Óceánia', 'vanuatu');
INSERT INTO Countries VALUES (244, 'Wallis és Futuna', 'Óceánia', 'wallisesfu');
INSERT INTO Countries VALUES (245, 'Északi Mariana-szigetek', 'Óceánia', 'eszakimari');
INSERT INTO Countries VALUES (246, 'Új-Kaledónia', 'Óceánia', 'ujkaledoni');
INSERT INTO Countries VALUES (247, 'Új-Zéland', 'Óceánia', 'ujzeland');
